Repository fumihub/enneagram, pull requests merged in 2022-02, with the labels that each got.

#11 #8 ci作成
  .github/workflows/ci.yml
  vue.config.js
Labels: タスク, 優先度　中

#12 Issue 3 質問画面の作成
  package.json
  public/data/questions.json
  src/router/index.js
  src/views/Question.vue
  src/views/Result.vue
Labels: タスク, 優先度　高

#14 #4 宝箱開くアニメーション画面作成
  package-lock.json
  src/components/BoxOpenAnimation.vue
Labels: タスク, 優先度　中

#15 Developマージ
  package-lock.json
  package.json
  public/data/questions.json
  public/image/question_background.png
  src/assets/closedBox.png
  src/assets/key.png
  src/assets/logo.png
  src/assets/logo.svg
  src/assets/openedBox.png
  src/assets/paper.png
  src/components/BoxOpenAnimation.vue
  src/components/EnneagramHome.vue
  src/components/HelloWorld.vue
  src/router/index.js
  src/views/About.vue
  src/views/Animation.vue
  src/views/Home.vue
  src/views/Question.vue
  src/views/Result.vue
Labels: タスク, 優先度　高

#17 #16 質問画面のjson取得エラーの修正
  src/views/Question.vue
  src/views/Result.vue
  vue.config.js
Labels: バグ

#18 Develop
  src/views/Question.vue
  src/views/Result.vue
  vue.config.js
Labels: タスク, 優先度　中
